baseURL = 'http://symphonious-granita-65551f.netlify.app'
languageCode = 'en-us'
title = 'My presentation website'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true